apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Build configuration for the runtime build.
  creationTimestamp: '2021-02-24T09:30:32Z'  
  name: as400-api-run
  namespace: 040102-savingsplan-01
  resourceVersion: '146319619' 
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'as400-api:latest'  
  resources:
    limits:
      cpu: '1'
      memory: 500M
    requests:
      cpu: '1'
      memory: 500M
  runPolicy: Serial
  source:
    dockerfile: >-
      FROM anywhere
      COPY 'as400-api.jar' /usr/local
      RUN chmod +x ./usr/local/as400-api.jar
      CMD ["java", "-jar", "./usr/local/as400-api.jar"]
    images:
      - as: null
        from:
          kind: ImageStreamTag
          name: 'as400-api-build:latest'
        paths:          
          - destinationDir: .
            sourcePath: /tmp/as400-api.jar
    type: Dockerfile
  strategy:
    dockerStrategy:
       from:
        kind: DockerImage
        name: 'fabric8/s2i-java:latest-java11'     
    type: Docker
  successfulBuildsHistoryLimit: 5 
status:
  lastVersion: 69
