# Logging #
#logging:
#  level:
#    org:
#      openlegacy: debug


management:
  health:
    defaults:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - health
          - olprojectinfo
          - metrics

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json

# Springdoc #
springdoc:
  pathsToMatch: /api/**
  swagger-ui:
    path: /swagger
  api-docs:
    path: /swagger/swagger.json
# OpenLegacy #
ol:
  # OpenLegacy Common Properties (OLCommonProperties) #
  common:
    cache:
      enabled: false
  license:
    key: eyJhbGciOiJSUzI1NiJ9.eyJwcm9kdWN0Ijoib3BlbmxlZ2FjeS1jb3JlIiwic3ViIjoib2wiLCJpc3N1ZWRfYXQiOiIyMDIxLTAyLTE2VDEyOjUxOjAxWiIsInZhbGlkX2ZvciI6OTB9.GCiyHStqaXC7xUHlPyN7OkoIhqyyn8s4LkshlSaHdg68N2lYJSBq3x9EFHaJroGtSJVZfde7AYd36xtRgWQdgeiOqVtm8HlgiGYVWQWdmiLwA1aPUzcCMO30c3VyNi__R2U_jhb7uWhUsLqSuTYT_tdTXtEtP_dbdZdNw7NCEiHu-vWGZBuS1Z2z2At0WWZbTx5bDRGCX1PvSsahySVEPfiPvH5g3aXFLEyoYuOQiwsGZakMFujQBhwQ1AuU7VGeY3vzbeJz1PA-yO476B6xFWkt0nLNDlz-LLv6WcyP0MJaCSoNoLBievO5l3f6mtiK2v1MWMbQYmiMI8bZeSTNLw
  security:
    db:
      init-schema: true
      clients:
        - client-id: client_id
          client-secret: '{noop}client_secret'
          scope: read,write,trust,ol_admin
          authorized-grant-types: client_credentials

---

# as400Sdk
ol:
  jt400:
    project:
      as400Sdk:
        host: as400.openlegacy.com
        user: OPENLEGA1
        password: '{cipher}b82101bb580a11f758216d05d1fcb84555d09da72a18856e8122a5cb1cb65524'
        code-page: 37
  license:
    key: eyJhbGciOiJSUzI1NiJ9.eyJwcm9kdWN0Ijoib3BlbmxlZ2FjeS1jb3JlIiwic3ViIjoib2wiLCJpc3N1ZWRfYXQiOiIyMDIxLTAyLTE2VDEyOjUxOjAxWiIsInZhbGlkX2ZvciI6OTB9.GCiyHStqaXC7xUHlPyN7OkoIhqyyn8s4LkshlSaHdg68N2lYJSBq3x9EFHaJroGtSJVZfde7AYd36xtRgWQdgeiOqVtm8HlgiGYVWQWdmiLwA1aPUzcCMO30c3VyNi__R2U_jhb7uWhUsLqSuTYT_tdTXtEtP_dbdZdNw7NCEiHu-vWGZBuS1Z2z2At0WWZbTx5bDRGCX1PvSsahySVEPfiPvH5g3aXFLEyoYuOQiwsGZakMFujQBhwQ1AuU7VGeY3vzbeJz1PA-yO476B6xFWkt0nLNDlz-LLv6WcyP0MJaCSoNoLBievO5l3f6mtiK2v1MWMbQYmiMI8bZeSTNLw




